// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: internal/introspection/service/proto/compiler_introspection.proto

package compiler_introsection

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntrospectionType int32

const (
	IntrospectionType_UNKNOWN  IntrospectionType = 0 // default value (optional)
	IntrospectionType_COMPILER IntrospectionType = 1
	IntrospectionType_VM       IntrospectionType = 2
)

// Enum value maps for IntrospectionType.
var (
	IntrospectionType_name = map[int32]string{
		0: "UNKNOWN",
		1: "COMPILER",
		2: "VM",
	}
	IntrospectionType_value = map[string]int32{
		"UNKNOWN":  0,
		"COMPILER": 1,
		"VM":       2,
	}
)

func (x IntrospectionType) Enum() *IntrospectionType {
	p := new(IntrospectionType)
	*p = x
	return p
}

func (x IntrospectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntrospectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_introspection_service_proto_compiler_introspection_proto_enumTypes[0].Descriptor()
}

func (IntrospectionType) Type() protoreflect.EnumType {
	return &file_internal_introspection_service_proto_compiler_introspection_proto_enumTypes[0]
}

func (x IntrospectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntrospectionType.Descriptor instead.
func (IntrospectionType) EnumDescriptor() ([]byte, []int) {
	return file_internal_introspection_service_proto_compiler_introspection_proto_rawDescGZIP(), []int{0}
}

type HeloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntrospectionType IntrospectionType `protobuf:"varint,1,opt,name=introspection_type,json=introspectionType,proto3,enum=compilerintrospection.IntrospectionType" json:"introspection_type,omitempty"`
	Capabilities      *CapabilityList   `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *HeloRequest) Reset() {
	*x = HeloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeloRequest) ProtoMessage() {}

func (x *HeloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeloRequest.ProtoReflect.Descriptor instead.
func (*HeloRequest) Descriptor() ([]byte, []int) {
	return file_internal_introspection_service_proto_compiler_introspection_proto_rawDescGZIP(), []int{0}
}

func (x *HeloRequest) GetIntrospectionType() IntrospectionType {
	if x != nil {
		return x.IntrospectionType
	}
	return IntrospectionType_UNKNOWN
}

func (x *HeloRequest) GetCapabilities() *CapabilityList {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HeloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId     string          `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Capabilities *CapabilityList `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *HeloResponse) Reset() {
	*x = HeloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeloResponse) ProtoMessage() {}

func (x *HeloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeloResponse.ProtoReflect.Descriptor instead.
func (*HeloResponse) Descriptor() ([]byte, []int) {
	return file_internal_introspection_service_proto_compiler_introspection_proto_rawDescGZIP(), []int{1}
}

func (x *HeloResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HeloResponse) GetCapabilities() *CapabilityList {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type CapabilityList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CapabilityList) Reset() {
	*x = CapabilityList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapabilityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityList) ProtoMessage() {}

func (x *CapabilityList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityList.ProtoReflect.Descriptor instead.
func (*CapabilityList) Descriptor() ([]byte, []int) {
	return file_internal_introspection_service_proto_compiler_introspection_proto_rawDescGZIP(), []int{2}
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Add fields related to the introspection events
	// Workaround while the api hasn't settled yet
	Json string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_introspection_service_proto_compiler_introspection_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type EventStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventStreamRequest) Reset() {
	*x = EventStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamRequest) ProtoMessage() {}

func (x *EventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamRequest.ProtoReflect.Descriptor instead.
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_introspection_service_proto_compiler_introspection_proto_rawDescGZIP(), []int{4}
}

type AbortSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *AbortSessionRequest) Reset() {
	*x = AbortSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionRequest) ProtoMessage() {}

func (x *AbortSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionRequest.ProtoReflect.Descriptor instead.
func (*AbortSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_introspection_service_proto_compiler_introspection_proto_rawDescGZIP(), []int{5}
}

func (x *AbortSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AbortSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbortSessionResponse) Reset() {
	*x = AbortSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionResponse) ProtoMessage() {}

func (x *AbortSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionResponse.ProtoReflect.Descriptor instead.
func (*AbortSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_introspection_service_proto_compiler_introspection_proto_rawDescGZIP(), []int{6}
}

var File_internal_introspection_service_proto_compiler_introspection_proto protoreflect.FileDescriptor

var file_internal_introspection_service_proto_compiler_introspection_proto_rawDesc = []byte{
	0x0a, 0x41, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x72, 0x6f,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x5f,
	0x69, 0x6e, 0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x69, 0x6e, 0x74,
	0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb1, 0x01, 0x0a, 0x0b, 0x48,
	0x65, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x57, 0x0a, 0x12, 0x69, 0x6e,
	0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65,
	0x72, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49,
	0x6e, 0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x11, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x65, 0x72, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x76,
	0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x0c, 0x63,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x69, 0x6e, 0x74, 0x72,
	0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x13, 0x41,
	0x62, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0x16, 0x0a, 0x14, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x36, 0x0a, 0x11, 0x49, 0x6e, 0x74,
	0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43,
	0x4f, 0x4d, 0x50, 0x49, 0x4c, 0x45, 0x52, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x4d, 0x10,
	0x02, 0x32, 0xb1, 0x02, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x49, 0x6e,
	0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x04, 0x48,
	0x65, 0x6c, 0x6f, 0x12, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x69, 0x6e,
	0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x48, 0x65, 0x6c, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x48, 0x65, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a,
	0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x29, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x72, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x69, 0x0a, 0x0c, 0x41, 0x62,
	0x6f, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65,
	0x72, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41,
	0x62, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_introspection_service_proto_compiler_introspection_proto_rawDescOnce sync.Once
	file_internal_introspection_service_proto_compiler_introspection_proto_rawDescData = file_internal_introspection_service_proto_compiler_introspection_proto_rawDesc
)

func file_internal_introspection_service_proto_compiler_introspection_proto_rawDescGZIP() []byte {
	file_internal_introspection_service_proto_compiler_introspection_proto_rawDescOnce.Do(func() {
		file_internal_introspection_service_proto_compiler_introspection_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_introspection_service_proto_compiler_introspection_proto_rawDescData)
	})
	return file_internal_introspection_service_proto_compiler_introspection_proto_rawDescData
}

var file_internal_introspection_service_proto_compiler_introspection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_introspection_service_proto_compiler_introspection_proto_goTypes = []interface{}{
	(IntrospectionType)(0),       // 0: compilerintrospection.IntrospectionType
	(*HeloRequest)(nil),          // 1: compilerintrospection.HeloRequest
	(*HeloResponse)(nil),         // 2: compilerintrospection.HeloResponse
	(*CapabilityList)(nil),       // 3: compilerintrospection.CapabilityList
	(*Event)(nil),                // 4: compilerintrospection.Event
	(*EventStreamRequest)(nil),   // 5: compilerintrospection.EventStreamRequest
	(*AbortSessionRequest)(nil),  // 6: compilerintrospection.AbortSessionRequest
	(*AbortSessionResponse)(nil), // 7: compilerintrospection.AbortSessionResponse
}
var file_internal_introspection_service_proto_compiler_introspection_proto_depIdxs = []int32{
	0, // 0: compilerintrospection.HeloRequest.introspection_type:type_name -> compilerintrospection.IntrospectionType
	3, // 1: compilerintrospection.HeloRequest.capabilities:type_name -> compilerintrospection.CapabilityList
	3, // 2: compilerintrospection.HeloResponse.capabilities:type_name -> compilerintrospection.CapabilityList
	1, // 3: compilerintrospection.CompilerIntrospection.Helo:input_type -> compilerintrospection.HeloRequest
	5, // 4: compilerintrospection.CompilerIntrospection.EventStream:input_type -> compilerintrospection.EventStreamRequest
	6, // 5: compilerintrospection.CompilerIntrospection.AbortSession:input_type -> compilerintrospection.AbortSessionRequest
	2, // 6: compilerintrospection.CompilerIntrospection.Helo:output_type -> compilerintrospection.HeloResponse
	4, // 7: compilerintrospection.CompilerIntrospection.EventStream:output_type -> compilerintrospection.Event
	7, // 8: compilerintrospection.CompilerIntrospection.AbortSession:output_type -> compilerintrospection.AbortSessionResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_introspection_service_proto_compiler_introspection_proto_init() }
func file_internal_introspection_service_proto_compiler_introspection_proto_init() {
	if File_internal_introspection_service_proto_compiler_introspection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapabilityList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_introspection_service_proto_compiler_introspection_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_introspection_service_proto_compiler_introspection_proto_goTypes,
		DependencyIndexes: file_internal_introspection_service_proto_compiler_introspection_proto_depIdxs,
		EnumInfos:         file_internal_introspection_service_proto_compiler_introspection_proto_enumTypes,
		MessageInfos:      file_internal_introspection_service_proto_compiler_introspection_proto_msgTypes,
	}.Build()
	File_internal_introspection_service_proto_compiler_introspection_proto = out.File
	file_internal_introspection_service_proto_compiler_introspection_proto_rawDesc = nil
	file_internal_introspection_service_proto_compiler_introspection_proto_goTypes = nil
	file_internal_introspection_service_proto_compiler_introspection_proto_depIdxs = nil
}
